### PR TITLE
Amended to support python nosetest XML output

### PR DESCRIPTION
**Pull request by aquamatt**
The nosetests.xml testsuite element does not have a `time` attribute and
so get_duration_from_junit_xml would break.

This has been patched such that nosetests.xml will parse, but backward
compatibility is retained.

This issue was found when using ci-metric-push on a Django project.

### CODE REVIEW

**Comment by tomazk** [comment]
@aquamatt thanks for this patch!

**Comment by tomazk** [comment]
@aquamatt can you perhaps add such a xml under https://github.com/Zemanta/ci-metric-push/tree/master/examples and send another pull request - thanks

**Comment by aquamatt** [comment]
Good poing @tomazk - I'll see to it

**Comment by tomazk** [comment]
@aquamatt thanks :+1:

**Pull request merged**
